datamodule:
  dataset_name: "gclip"
  data_path: "../data/captions.csv"
  img_dir: "../data/images"
  tokenizer_name: "bert-base-uncased"
  img_size: 224
  txt_max_length: 200
  val_size: 0.2
  test_size: 0.2
  batch_size: 32
  num_workers: 4
  pin_memory: true

model:
  is_trainable: true
  use_pretrained: true
  img_model_name: "vit_base_patch16_224"
  img_embedding: 768
  text_model_name: "bert-base-uncased"
  text_embedding: 768
  projection_dim: 256
  dropout: 0.1
  temperature: 1.0
  loss_fn: "cross_entropy"
  label_type: "game"

train:
  seed: 42
  img_encoder_lr: 1e-4
  text_encoder_lr: 1e-5
  proj_head_lr: 1e-3
  weight_decay: 1e-3
  patience: 1
  factor: 0.8
  epochs: 20
  ckpt_dir: "../src/exp"
  save_top_k: 3
  eval_step: 200

cuda:
  use_multi_gpu: true
  use_amp: true
